"""initial migration

Revision ID: a9b38910354b
Revises: 
Create Date: 2025-05-05 01:20:23.119490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b38910354b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yemek', sa.String(), nullable=True),
    sa.Column('mutfagi', sa.String(), nullable=True),
    sa.Column('sure', sa.Integer(), nullable=True),
    sa.Column('malzeme', sa.String(), nullable=True),
    sa.Column('yapilisi', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_id'), 'recipes', ['id'], unique=False)
    op.create_index(op.f('ix_recipes_yemek'), 'recipes', ['yemek'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('vitamins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vitamins_id'), 'vitamins', ['id'], unique=False)
    op.create_index(op.f('ix_vitamins_name'), 'vitamins', ['name'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expiration_date', sa.Float(), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=True),
    sa.Column('is_consumed', sa.Boolean(), nullable=True),
    sa.Column('is_discarded', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('user_vitamin_status',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vitamin_id', sa.Integer(), nullable=False),
    sa.Column('current_level', sa.Float(), nullable=True),
    sa.Column('recommended_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vitamin_id'], ['vitamins.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'vitamin_id')
    )
    op.create_table('product_vitamins',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('vitamin_id', sa.Integer(), nullable=False),
    sa.Column('amount_mg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['vitamin_id'], ['vitamins.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'vitamin_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_vitamins')
    op.drop_table('user_vitamin_status')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_vitamins_name'), table_name='vitamins')
    op.drop_index(op.f('ix_vitamins_id'), table_name='vitamins')
    op.drop_table('vitamins')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_recipes_yemek'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_id'), table_name='recipes')
    op.drop_table('recipes')
    # ### end Alembic commands ###
